### ISSUE TITLE
New docker build?

### ISSUE THREAD

**Issue by SpangleLabs** [arnarg/plex_exporter#11]
Looks like the the image on dockerhub is 2 years out of date:
https://hub.docker.com/r/granra/plex_exporter

Could that be updated?

**Comment by arnarg** [comment]
The plex_exporter image is build on a distroless image so it contains nothing except the compiled plex_exporter binary along with root CA certificates. Therefor there is not much security issue with using the older image.

It could however be missing some new root certificates. I'll try to rebuild and push soon.

**Comment by SpangleLabs** [comment]
Yeah, there's no security issue, but it doesn't include the new health check endpoint: #9

**Comment by arnarg** [comment]
I see. I created a new release https://github.com/arnarg/plex_exporter/releases/tag/v0.2.3

**Comment by SpangleLabs** [comment]
Thank you!
