### ISSUE TITLE
[feature] Choose server(s) to obtain metrics for

### ISSUE THREAD

**Issue by frebib** [arnarg/plex_exporter#3]
I have several Plex servers linked to my account, only one of which I actually own. Each scrape generates one error for every server I am not an admin on:
```
ERRO[0064] Could not get metrics for server "name" ...
```

I know that I don't want to scrape these servers, so it would be useful if I could explicitly list the server at runtime that I want to scrape metrics for, preferably a `--server=<address>` flag.

Additionally I'd like the option to point the exporter directly at the Plex server address, bypassing the plex api- I know where my server is and I don't want/need to trust Plex to help me out there

**Comment by arnarg** [comment]
> ... it would be useful if I could explicitly list the server at runtime that I want to scrape metrics for, preferably a --server=\<address\> flag.

Adding a whitelist of server addresses would be possible.

> Additionally I'd like the option to point the exporter directly at the Plex server address, bypassing the plex api- I know where my server is and I don't want/need to trust Plex to help me out there

I believe using plex.tv api is the only way to authenticate against the server. So you would need to add the IP of the machine running plex_exporter to the list of addresses allowed without auth. This should be possible as well.

**Comment by frebib** [comment]
I'm not massively familiar with the Plex server endpoints but afaik all you need is the token (`X-Plex-Token`) to communicate with the server, the same as you would with the Plex API- I could be wrong though. 

Thanks very much, this exporter is really useful :)

**Comment by arnarg** [comment]
> afaik all you need is the token (X-Plex-Token) to communicate with the server, the same as you would with the Plex API

This token is acquired with either endpoint `https://plex.tv/users/sign_in.json` or `https://plex.tv/pins`. The former being username and password (I think) and latter the one I use and makes plex_exporter a "plex device" with its own authentication token that can be revoked at any point (go to Settings->Autorized Devices). I'd rather keep it that way.

I think it would be possible to add a flag that skips getting the token and relies on not needing auth. But afaik not using plex.tv at all during authentication is not possible.

**Comment by arnarg** [comment]
FYI, with `--auto-discover` flag you will only get Plex server you own (at least that's what I assume the property `owned` means). Please give that a try.
