### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by onedr0p** [arnarg/plex_exporter#6]
Hi, it would be awesome if you could commit a Grafana dashboard (json) file to the repo.

Thanks!

**Comment by TheThirdBeast** [comment]
Anyone has a Grafana template (dashboard id) compatible with this exporter ? Starting to work on it but from scratch it is a bit discouraging.

**Comment by alexfornuto** [comment]
@TheThirdBeast did you end up making one? I'm in the same place you were a year ago.
